### ISSUE TITLE
Playmumusic keeps on Crashing.

### ISSUE THREAD

**Issue by pookito** [artemanufrij/playmymusic#66]
I amusing Elementary OS Loki, and I decided to purchase the software, since I did not like the default music app that Elementarry comes with. Sadly, it's been a week and I am not able to use it 👎 😿 .  I tried to read other post and decided to run it in a terminal and the following happened before it crashed. It read a few albums and then segmentation fault (core duped) pops up.  **What can I do to make this app to works on my computer**.  Using a Lenovo i3 4gb of Ram 500 GB of hard disk.

com.github.artemanufrij.playmymusic 
ARTIST ID:  (FILHO PRÓDIGO / ARAUTOS DO REI)
ARTIST ID: 471f35c4-5641-4f98-9108-afb841af5692 (Heaven / BeBe & CeCe Winans)
ARTIST ID:  (I Love Jazz / Arrested Development)
ARTIST ID:  (Sweet Pain / Anthony David)
ARTIST ID: 8429c63c-7004-4aae-849b-fde0ea574501 (Testify To Love / Avalon)
Segmentation fault (core dumped)

**Comment by artemanufrij** [comment]
hey @pookito thanks for feedback. i need some informations:
* is your music library local or mounted from a network device?
* if network device: SMB/NFS...?
* which formats have your music files? (mp3,ogg,…)
* how many files have you in your library?

**Comment by artemanufrij** [comment]
I can't reproduce it :cry:

**Comment by pookito** [comment]
Hey @artemanufrij, Thank you for writing to me so quick.  It is nice to see that the developer cares that much.  👍 💯 🥇 That is for you bro.

The answer is that my music library is in my hard drive.  It is not connected to the network via smb or nfs or any other.  They are a combination of mp3s and a.  I do have 30.2 gb, 222 folders and 92 additional mp3 files.  I hope that helps.  One of the reason why I got it was that the add said it was design for large libraries.

**Comment by artemanufrij** [comment]
@pookito yeah... I have ~8000 music files (80GB). I tryed it > 10 times and it never chrashed.

I have no idea how can I test it :(

![bildschirmfoto von 2018-02-11 20 38 52](https://user-images.githubusercontent.com/16517095/36077485-c29e61d8-0f6b-11e8-911c-195eca0ba705.png)

**Comment by artemanufrij** [comment]
hey @pookito  you could help me to debug it:
```
$ gdb com.github.artemanufrij.playmymusic
r
(wait for segfault)
bt full
```

send me please the result after `bt full`

**Comment by pookito** [comment]
Thank you for writing back to me.  I wish I can help more.  But if you would like to show me around the ropes I'll be willing to help out with more projects.  Here is what you asked for: 

GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from com.github.artemanufrij.playmymusic...(no debugging symbols found)...done.
(gdb) bt full
No stack.
(gdb) 

PS, I did not see the segfault.

sad pat is that when I ran the app at the command line the following happened:  

com.github.artemanufrij.playmymusic 
ARTIST ID:  (Sweet Pain / Anthony David)
ARTIST ID:  (FILHO PRÓDIGO / ARAUTOS DO REI)
ARTIST ID: 471f35c4-5641-4f98-9108-afb841af5692 (Heaven / BeBe & CeCe Winans)
ARTIST ID:  (I Love Jazz / Arrested Development)
ARTIST ID: 8429c63c-7004-4aae-849b-fde0ea574501 (Testify To Love / Avalon)
ARTIST ID: 8429c63c-7004-4aae-849b-fde0ea574501 (The Creed / Avalon)
Segmentation fault (core dumped)

Then it crashed.

**Comment by artemanufrij** [comment]
@pookito put `bt full` into command line after `Segmentation fault (core dumped)`

**Comment by pookito** [comment]
It seems that I don't have that package installed.  I tried the following:

 bt full
bt: command not found
pookito@pookito-Lenovo-S41-70:~$ sudo apt install bt
btag             btanks-data      btest            bti              btrbk            btrfs-tools-dbg  btyacc
btanks           btcheck          btfs             btpd             btrfs-tools      btscanner        
pookito@pookito-Lenovo-S41-70:~$ sudo apt install bt
btag             btanks-data      btest            bti              btrbk            btrfs-tools-dbg  btyacc
btanks           btcheck          btfs             btpd             btrfs-tools      btscanner        
pookito@pookito-Lenovo-S41-70:~$ sudo apt install bt
which one of them is the one I need to install to do this?

**Comment by artemanufrij** [comment]
@pookito you don't have to install `bt` it's a part of `dbg`

1. command:
`gdb com.github.artemanufrij.playmymusic`

2. command:
press `r` + enter for run
wait for Segmentation fault

3. command:
`bt full`

**Comment by artemanufrij** [comment]
PS: meybe you have to install `gdb`

**Comment by pookito** [comment]
Thank you for the quick reply here is what I got: 

[New Thread 0x7ffcbee21700 (LWP 20911)]
[New Thread 0x7ffcbd61e700 (LWP 20912)]
[Thread 0x7ffddf061700 (LWP 18460) exited]
[New Thread 0x7ffddf061700 (LWP 20913)]
[New Thread 0x7ffcbce1d700 (LWP 20914)]
[New Thread 0x7ffcbc61c700 (LWP 20915)]
[New Thread 0x7ffcbbe1b700 (LWP 20916)]
[New Thread 0x7ffcbae19700 (LWP 20917)]
[New Thread 0x7ffcba618700 (LWP 20918)]
[New Thread 0x7ffcb9e17700 (LWP 20919)]
[New Thread 0x7ffcb9616700 (LWP 20920)]
[New Thread 0x7ffcb8e15700 (LWP 20921)]
[New Thread 0x7ffcb8614700 (LWP 20922)]
[New Thread 0x7ffcb6e11700 (LWP 20923)]
[New Thread 0x7ffcb6610700 (LWP 20924)]
[New Thread 0x7ffcb5e0f700 (LWP 20925)]
[New Thread 0x7ffcb560e700 (LWP 20926)]
[New Thread 0x7ffcb4e0d700 (LWP 20927)]
[New Thread 0x7ffcb3e0b700 (LWP 20928)]
[New Thread 0x7ffcb360a700 (LWP 20929)]
[New Thread 0x7ffcb2e09700 (LWP 20930)]
[New Thread 0x7ffcb2608700 (LWP 20931)]
[New Thread 0x7ffcb1e07700 (LWP 20932)]
[New Thread 0x7ffcb1606700 (LWP 20933)]
[New Thread 0x7ffcb0e05700 (LWP 20934)]

Thread 4458 "com.github.arte" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffcb1606700 (LWP 20933)]
0x000000000042e0b5 in ?? ()
(gdb) bt full
#0  0x000000000042e0b5 in ?? ()
No symbol table info available.
#1  0x00007ffff4f66bb5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#2  0x00007ffff22596ba in start_thread (arg=0x7ffcb1606700) at pthread_create.c:333
        __res = <optimized out>
        pd = 0x7ffcb1606700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140723284371200, 5708919307910848191, 0, 140737488343647, 140723284371904, 
                12427104, -5709643908512407873, -5708941902877876545}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 
              0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#3  0x00007ffff4a2e41d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
No locals.
(gdb) 
I hope that helps, if not, please let me know I'd like to help more.  😄

**Comment by artemanufrij** [comment]
omg... I can't reproduce it :confounded:
